[package]
name = "day19"
version = "0.1.0"
authors = ["Aseem Dua <aseem.dua@here.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
itertools = "0.9.0"
text_io = "0.1.8"